[build]
  command = "npm run build"
  functions = "lambda"
  publish = "web"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"

[[redirects]]
  from = "/rss/*"
  to = "http://www.deltazeus.com.s3-website-us-east-1.amazonaws.com/:splat"