[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/location"
  to = "/.netlify/functions/location"
  status = 200
  force = true

[[redirects]]
  from = "/feeds"
  to = "/.netlify/functions/feeds"
  status = 200
  force = true

[[redirects]]
  from = "/feeds/*"
  to = "/.netlify/functions/feeds/:splat"
  status = 200
  force = true

[dev]
  command = "npm run dev"
  targetPort = 4321
  port = 8888


