[build]
  command = "npm run build"
  functions = "lambda"
  publish = "web"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/rss/*"
  to = "https://www.deltazeus.com.s3-website-us-east-1.amazonaws.com/rss/:splat"
  force = true
  status = 200