org: ddamato
app: deltazeus
service: deltazeus-service

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  active:
    handler: api/active.handler
    environment:
      DZ_DARKSKY_API_SECRET: '${param:DZ_DARKSKY_API_SECRET}'
      DZ_GEOCODEXYZ_API_KEY: '${param:DZ_GEOCODEXYZ_API_KEY}'
      DZ_AWS_ACCESS_KEY: '${param:DZ_AWS_ACCESS_KEY}'
      DZ_AWS_SECRET_KEY: '${param:DZ_AWS_SECRET_KEY}'
    events:
      - http:
          path: active
          method: get
          cors: true
  cron:
    handler: api/cron.handler
    environment:
      DZ_DARKSKY_API_SECRET: '${param:DZ_DARKSKY_API_SECRET}'
      DZ_GEOCODEXYZ_API_KEY: '${param:DZ_GEOCODEXYZ_API_KEY}'
      DZ_AWS_ACCESS_KEY: '${param:DZ_AWS_ACCESS_KEY}'
      DZ_AWS_SECRET_KEY: '${param:DZ_AWS_SECRET_KEY}'
    events:
      - http:
          path: cron
          method: get
          cors: true
  forecast:
    handler: api/forecast.handler
    environment:
      DZ_DARKSKY_API_SECRET: '${param:DZ_DARKSKY_API_SECRET}'
      DZ_GEOCODEXYZ_API_KEY: '${param:DZ_GEOCODEXYZ_API_KEY}'
      DZ_AWS_ACCESS_KEY: '${param:DZ_AWS_ACCESS_KEY}'
      DZ_AWS_SECRET_KEY: '${param:DZ_AWS_SECRET_KEY}'
    events:
      - http:
          path: forecast
          method: get
          cors: true
  rss:
    handler: api/rss.handler
    environment:
      DZ_DARKSKY_API_SECRET: '${param:DZ_DARKSKY_API_SECRET}'
      DZ_GEOCODEXYZ_API_KEY: '${param:DZ_GEOCODEXYZ_API_KEY}'
      DZ_AWS_ACCESS_KEY: '${param:DZ_AWS_ACCESS_KEY}'
      DZ_AWS_SECRET_KEY: '${param:DZ_AWS_SECRET_KEY}'
    events:
      - http:
          path: rss
          method: get
          cors: true
  thresholds:
    handler: api/thresholds.handler
    environment:
      DZ_DARKSKY_API_SECRET: '${param:DZ_DARKSKY_API_SECRET}'
      DZ_GEOCODEXYZ_API_KEY: '${param:DZ_GEOCODEXYZ_API_KEY}'
      DZ_AWS_ACCESS_KEY: '${param:DZ_AWS_ACCESS_KEY}'
      DZ_AWS_SECRET_KEY: '${param:DZ_AWS_SECRET_KEY}'
    events:
      - http:
          path: thresholds
          method: get
          cors: true

