service: sls-typescript-rest-api-with-dynamodb

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-east-1

functions:
  create:
    handler: functions/rss.handler
    events:
      - http:
          path: rss
          method: get
  create:
    handler: functions/cron.handler
    events:
      - http:
          path: cron
          method: get
  create:
    handler: functions/forecast.handler
    events:
      - http:
          path: forecast
          method: get

