org: ddamato
app: deltazeus
service: deltazeus-service

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  cron:
    handler: functions/cron.handler
    events:
      - http:
          path: cron
          method: get
  forecast:
    handler: functions/forecast.handler
    events:
      - http:
          path: forecast
          method: get
  rss:
    handler: functions/rss.handler
    events:
      - http:
          path: rss
          method: get

