name: cron curl

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://api.deltazeus.com/cron